#!/bin/bash
set -e

# keypass - Manage passwords with Keybase
# Built by: Toby Padilla <tobypadilla@gmail.com>
# http://keybase.io/toby | http://github.com/toby | http://twitter.com/toby

# Your keybase.io user name
KEYBASE_USER=toby

# Directory to store your encrypted passwords file
PASS_DIR=~/Dropbox
PASS_FILE=$PASS_DIR/keypass.txt.asc

usage() {
  echo "usage: $(basename $0) {gen CHARACTERS | list [\"TERM\"] | add URL USER PASS [\"DESC\" | interactive}"
}

decrypted_passes() {
  echo "$(keybase decrypt -i $PASS_FILE)"
}

encrypt_passes() {
  keybase encrypt $KEYBASE_USER -o $PASS_FILE
}

list() {
  PASSES=$(decrypted_passes)
  echo -e "$PASSES" |
  column -t -s $'\t' |
  ([[ -n "$1" ]] && grep -i "$1" || cat)
}

add() {
  # Domain, user and pass are not optional
  if [[ -n "$1" && -n "$2" && -n "$3" ]];
  then
    PASS_ENTRY="$1\t$2\t$3\t$4"
    # Don't try to decrypt a file that doesn't exist
    if [ ! -f $PASS_FILE ]
    then
      PASSES="$PASS_ENTRY"
    else
      # I would use sed for this but it's broken on OS X
      PASSES=$(decrypted_passes)
      PASSES=$(printf "$PASSES\n$PASS_ENTRY")
    fi

    printf "$PASSES" | encrypt_passes
  else
    usage
  fi
}

gen() {
  openssl rand -base64 $1
}

interactive() {
  TEMP=$(mktemp)
  PASSES=$(decrypted_passes)
  echo "$PASSES" > $TEMP
  "${EDITOR:-vi}" $TEMP
  cat $TEMP | encrypt_passes
  rm $TEMP
}

case "$1" in
  'l'|list) list "$2";;
  'a'|add) add "$2" "$3" "$4" "$5";;
  'g'|gen) gen "$2";;
  'i'|interactive) interactive;;
  *) usage;;
esac
